### ISSUE TITLE
Update key columns in rw_table

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-specs#127]
In https://github.com/appliedzkp/zkevm-specs/pull/118 we updated the state circuit spec.
Previously there were 4 key columns in `rw_table`.  In order to maintain keys of type ethereum address separate, we introduced a new column (and made some rearangements of key usage).

We need to update `table.py` and the usage of rw_table accordingly.

**Comment by ashWhiteHat** [comment]
Is this issue similar to following issue?
https://github.com/privacy-scaling-explorations/zkevm-specs/issues/275

When I was working on above issue, I found some missing fields and constraints.
I can add missing fields and constraints.
I would also like to rename some component.

For example, 
- `check_start` -> `build_start_constraints`
-  `Row` -> `ConstraintBuilder`

Should I rename according to zkevm-circuits?

**Comment by ed255** [comment]
Resolved in #159
