### ISSUE TITLE
Discussion about RLC requirements and alternatives

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-specs#135]
# Introduction

In the current design we use the RLC to compress an EVM Word into a single field element, allowing us to encode a word witness in a single cell, and enforce equality between words using a single cell for each word.

The RLC is defined as:
```
RLC(w) = w[0] + w[1] * r + w[2] * r**2 + w[3] * r**3 + ... + w[31] * r**31
```
Where `w` is the encoded word, and `w[i]` is the i-th byte of the word in little endian, and `r` is a random value (challenge for the prover)

For more details see https://hackmd.io/XuF2HOC4SeC7Q35niaaF1A?view

# Observation

From the definition of the `RLC` function we can see that when `0 <= w <= 255` the `RLC` acts as the identity function.  This fact is currently used in some opcode implementations:

- `BYTE`, `COMPARATOR` and `SIGNED_COMPARATOR` opcode gadgets rely on the fact that `for x in [0, 255], RLC(x) = x`
    - This means that a cell that is constrained to be between 0 and 255, can be used in a place where that same value in RLC is expected, skipping the RLC encoding expression.
- `JUMPI` relies on the fact that `RLC(0) = 0` and `for all w != 0, RLC(w) != 0`.
    - This means that we can test whether an RLC encoded value is different than 0 without doing the RLC decoding into bytes.
- [`ISZERO`](https://github.com/appliedzkp/zkevm-specs/pull/157) relies on the fact that `RLC(0) = 0` and `RLC(1) = 1`.
    - This means that we can test wether an RLC encoded value is 0 or 1 without doing the RLC decoding into bytes.

# Alternative proposal

Based on the previous observation and my understanding of the requirements of the RLC, could we use this expression instead to compress words into field elements?
```
F(w) = w[0] + w[1] * 256 + w[2] * 256**2 + w[3] * 256**3 + ... + w[30] * 256**30 + w[31] * r
```
This expression has the property that for values with less/equal than 248 bits, it's the identity function.  This could be useful for example when working with address type, as we could skip the RLC encoding expression.  Or for values that represent memory offsets, gas values, etc.

Note1: that when using this expression in the circuit, we need to constraint the range of each `w[i]` cell to be between 0 and 255 (just like we do with the RLC).

Note2: this expression would only work for compression of words; for variable length byte arrays a different strategy is needed (we could keep the RLC for that).

**Comment by CPerezz** [comment]
Discussing now with @ed255 about keccak talbe here: https://github.com/appliedzkp/zkevm-specs/pull/150#discussion_r832128562

We saw that would be really nice to finally define this so that we can make further considerations in our circuit designs.
Maybe a topic to discuss in the weekly call @barryWhiteHat @ChihChengLiang @ed255 ?

**Comment by ed255** [comment]
The Word RLC will be superseded by https://github.com/privacy-scaling-explorations/zkevm-specs/issues/216 so this discussion is no longer important.
