### ISSUE TITLE
Execution of calling to account with empty code

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-specs#146]
In Ethereum yellowpaper, the message call function <img src="https://render.githubusercontent.com/render/math?math={\color{white}{\Theta}}#gh-dark-mode-only" /><img src="https://render.githubusercontent.com/render/math?math={\Theta}#gh-light-mode-only" /> [^yellowpaper-ch-8] has not specifically mentioned how to handle when the recipient has empty code (please correct me if you find the definition somewhere), and I believe its due to the following 2 natures of EVM to save special handler for such case:

1. A `STOP` will be returned when indexing code out of range
2. `STOP` costs no gas and mutates nothing of global state

So most EVM implementations choose to skip the execution and just empty the return data for efficiency. However, in our case, adding an extra branch in such a complicated opcode is not a good thing (see its implementation in [`62ffc07`](https://github.com/appliedzkp/zkevm-specs/pull/82/commits/62ffc07a077a0c54c51f4b70cc334fe88109015a)), so it seems a good trade a sacrifice a `STOP` step when there is a call to empty code, to gain a simpler circuit implementation (for `BeginTx` and `*CALL*`). But it relies on 2 assumptions:

1. No specific handler will be proposed to handle message call when the recipient has empty code
2. `STOP` keeps costing no gas and mutating nothing of global state

Which seem fine to assume due to the backward compatibility. Note that upcoming EOF only changes the behavior of contract deployment (to gain future execution efficiency on normal machine), and doesn't change the definition of message call function.

(creation with empty initcode seems to have the same situation)

Any feedback is appreciated.

[^yellowpaper-ch-8]: https://ethereum.github.io/yellowpaper/paper.pdf chapter 8

**Comment by ed255** [comment]
The proposal of executing a single STOP when the account doesn't have code seems completely reasonable and sound to me!

I see this as the same behavior that happens in the execution when the end of the bytecode is reached without a terminating opcode, and then a byte outside the code is read as 0x00 leading to the execution of the STOP opcode; but here we're just encountering this behavior at the first step.

I also find this reasonable because all accounts have a bytecode array, it's just that by default it's an array of length 0, so the read at index 0 returns 0x00 (STOP) as you mentioned.

**Comment by han0110** [comment]
Yeah, `STOP` needs to deal with "indexing code out of range" anyway, which is a TODO in #100 since we haven't decided how to retrieve code length (if no new proposal, I would just extend bytecode circuit as you proposed in https://github.com/appliedzkp/zkevm-specs/issues/102#issuecomment-1021313975 after I finish `CALL`).

**Comment by icemelon** [comment]
This makes sense to me! IIUC, it's just handled in the lookup to bytecode table, and it won't affect the bytecode circuit and storage circuit when computing the hash of the account with empty bytecode array. Am I correct?

**Comment by han0110** [comment]
> it's just handled in the lookup to bytecode table, and it won't affect the bytecode circuit and storage circuit when computing the hash of the account with empty bytecode array.

I think Bytecode circuit still needs to be updated to support tag (`Length` and `Byte`), then for `ExecutionState::STOP`, we checks either:

1.  `bytecode_lookup(code_hash, Length, 0).value == program_counter`
2. `bytecode_lookup(code_hash, Byte, program_counter).value == Opcode::STOP`

**Comment by icemelon** [comment]
> I think Bytecode circuit still needs to be updated to support tag (`Length` and `Byte`), then for `ExecutionState::STOP`, we checks either:
> 
> 1. `bytecode_lookup(code_hash, Length, 0).value == program_counter`
> 2. `bytecode_lookup(code_hash, Byte, program_counter).value == Opcode::STOP`

Makes sense. @roynalnaruto is working on the support `Length` and `Byte` in the Bytecode lookup table. You can also handle this issue at the same time.

**Comment by ed255** [comment]
Currently the spec and impl define the call with empty code as a special case with their associated constraints.  Closing this as we have a working solution for now.  May revisit in the future.
