### ISSUE TITLE
Missing `ExecutionState` transition constraint to special ones

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-specs#171]
Currently in `CALLDATACOPY` and `CODECOPY` it defines the next step' state and auxiliary data when the `length` of bytes to copy is greater than `0`. But when the `length` is `0`, it doesn't define the next step's state and auxiliary data, which allows a malicious prover to start to copy from any source to any destination.

Such special `ExecutionState` transition needs to be taken extra care of because they are not implicitly constraint by `code_source` and increasing `program_counter`, we have already constraint from which can transit to them:

https://github.com/appliedzkp/zkevm-specs/blob/a6b8a207ba7189d79987e03a5723e09e175d2ec5/src/zkevm_specs/evm/instruction.py#L149-L157

But it doesn't mean those valid previous state always transit to them (e.g. `BeginTx` can't transit to `EndTx` when there is some code to be executed).

So 2 approach to make `CALLDATACOPY` and `CODECOPY` (also with `Copy*To*` themselves) well defined:
1. Constraint next step's state is _not_ `CopyToMemory` when `length` is `0`
2. Constraint next step's state to be `CopyToMemory` with properly auxiliary data no matter the `length` is, and the next step would just be a dummy `CopyToMemory` with `bytes_left` as `0` (sacrificing one dummy step to gain less constraint)

cc @icemelon

**Comment by icemelon** [comment]
Agree. It is a loophole in the EVM circuit.

I think the 2nd approach is better because in option 1 we need to constrain the next step's state cannot be any of  `Copy*To*` states. But in the long term, we should eliminate all `Copy*To*` states and use copy circuit to perform the copy.

I can work on a temporary fix with option 2 for now. WDYT?

**Comment by han0110** [comment]
Yeah, a fix by option 2 sounds good to me.

**Comment by DreamWuGit** [comment]
`Log ` should have the same issue when `CopyToLog`

**Comment by ed255** [comment]
This has been resolved with the addition of the CopyCircuit which led to the removal of the CopyToFoo virtual steps.
