### ISSUE TITLE
add markdown spec for `begin_tx` & `end_tx` gadgets

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-specs#180]
currently there is only python implementation for `begin_tx` & `end_tx` gadgets, I think it is better to add markdown spec as well like other auxiliary gadgets(`CopyToMemory`, `CopyToLog` etc.) , which is useful for better understanding and reading !

Glad to know your opinions!

**Comment by ed255** [comment]
You can add `end_block` to the list :P

**Comment by ChihChengLiang** [comment]
Adding markdown spec for `begin_tx`, `end_tx`, `CopyToMemory`, `CopyToLog`, and `end_block` sounds like a good idea to me!

**Comment by ed255** [comment]
Note that `CopyToMemory` and `CopyToMemory` execution state no longer exits (the became obsolete with the copy circuit).

**Comment by rrtoledo** [comment]
I added some comments/questions on the PR directly
