### ISSUE TITLE
Specify constraints for TxRefund in State circuit

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-specs#244]

**Comment by ashWhiteHat** [comment]
Add missing constraints here
https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/state.py#L326

**Comment by ed255** [comment]
I checked the current usage of TxRefund in the evm circuit and currently its:
- written by SSTORE (we can leave SELFDESTRUCT in the back for now)
- read by EndTx (to actually do the refund)

I think the only constraint that is needed is:
```python
    # 7.2 First access for a set of all keys
    # - If READ, value must be 0
    if not all_keys_eq(row, row_prev) and row.is_write == 0:
        assert row.value == 0
```
Which already exists for other targets. This will guarantee that if there's no refund, in EndTx the only value that can be read is a 0.
