### ISSUE TITLE
Update account/storage lookups to check non-existence

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-specs#259]
Currently the specs of opcodes that check the state assume that even though an account may not exists, a lookup to an account field will succeed with the default value as a result.  This will not be the case as the MPT will not have entries of default values for non-existing leafs, but instead will support lookups that prove the non-existence of an account.

This means that all opcodes that perform account field lookups must do 2 lookups:
1. Account existence.
2. Account field.
If the account doesn't exist, the account field lookup is skipped and a default value is used.

Also, currently the way to check that an account doesn't exists consist on doing 3 lookups to check:
- `nonce = 0`
- `balance = 0`
- `codeHash = emptyCodeHash`

We should replace those 3 lookups by a single lookup of account existence.

Depends on https://github.com/privacy-scaling-explorations/zkevm-specs/issues/249

- [x] `BALANCE`  https://github.com/privacy-scaling-explorations/zkevm-specs/pull/248
- [x] `EXTCODEHASH` https://github.com/privacy-scaling-explorations/zkevm-specs/pull/305
- [x] `EXTCODECOPY` https://github.com/privacy-scaling-explorations/zkevm-specs/pull/344
- [x] `EXTCODESIZE` https://github.com/privacy-scaling-explorations/zkevm-specs/pull/341
- [ ] `CALL` assigned to @ashWhiteHat 
- [x] `CALLCODE` https://github.com/privacy-scaling-explorations/zkevm-specs/pull/335
- [x] `DELEGATECALL` https://github.com/privacy-scaling-explorations/zkevm-specs/pull/335
- [x] `STATICCALL` https://github.com/privacy-scaling-explorations/zkevm-specs/pull/335
- [ ] `SELFDESTRUCT` On hold. See: https://github.com/privacy-scaling-explorations/zkevm-specs/issues/259#issuecomment-1344003567
- [x] `SLOAD` https://github.com/privacy-scaling-explorations/zkevm-specs/pull/345
- [x] `SSTORE` https://github.com/privacy-scaling-explorations/zkevm-specs/pull/345

**Comment by eliseygusev** [comment]
Hey, @ed255 would love to partially help with that issue, can I do that? As far as I understand one would just need to update the spec using AccountFieldTag.NonExisting, am I right? Is there a catch? 
Also, was wondering about the workflow overall, does one also need to update circuits or the updates are done separately?

**Comment by ed255** [comment]
> Hey, @ed255 would love to partially help with that issue, can I do that? 

Hi @eliseygusev and welcome!

You are very welcome to help with this issue! :D

I would propose that you start with the update of `EXTCODESIZE`, and make a PR for it. 

> As far as I understand one would just need to update the spec using AccountFieldTag.NonExisting, am I right? Is there a catch? 

Yes, you should the same update as here:
https://github.com/privacy-scaling-explorations/zkevm-specs/pull/305/files

What you need to consider is that a lookup of an account field will not be possible if the account doesn't exist.  And a lookup of non existing will not be possible if the account exists.  So the solution is to conditionally do one lookup or the other (as they are contradictory).  Another reference is the `BALANCE` opcode: https://github.com/privacy-scaling-explorations/zkevm-specs/blob/33e78c0d5f3baae05d6a51cedc6df387efa48532/src/zkevm_specs/evm/execution/balance.py#L19-L22

Also note that in polynomial constraints there are no if/else.  In the python implementation we may write them because they show the intent of the constraint in a more clear way.  When translating this to actual polynomial constraints there are mechanisms to enable a constraint or lookup conditionally on an expression (enabled when expression is !=0, disabled when expression is 0).  This won't affect this tasks in the spec scope (only the halo2 circuit implementation), but it's good to have it in mind!

> Also, was wondering about the workflow overall, does one also need to update circuits or the updates are done separately?

For our development workflow, we have some notes here https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/CONTRIBUTING.md and to answer your question: in this repository we keep a textual spec of each opcode and circuit parts of the zkevm (under the `/specs` directory), and a simplified python implementation of the circuits (in `/src`, with corresponding tests in `/tests`).  When submitting a PR to this repository, the part in `/specs` and `/src` should match.  Afterwards we do the corresponding implementation of the circuit in halo2 in https://github.com/privacy-scaling-explorations/zkevm-circuits
The halo2 circuit implementation part is done separately, but sometimes the same contributor will do both (spec and circuit).

**Comment by eliseygusev** [comment]
Thank you so much for clarifying! I will try to update the spec for  `EXTCODESIZE` this weekend and check whether I am capable of updating the circuit as well.

**Comment by ed255** [comment]
@CPerezz is currently working on updating `SLOAD` and `SSTORE`

@eliseygusev So previously I recommended you to start working on updating `EXTCODESIZE` but it turns out we don't have this opcode specified yet (Thanks @CPerezz for noticing!), so I would suggest to work on `EXTCODECOPY` instead.  For that one, the logic should be:
- If the account exists
  - 1 read its code_hash
  - 2 then get it's size and proceed with the copy (using the copy circuit via the copy table lookup).  This is what's currently implemented
- If the account doesn't exist
  - 1 set code_hash to the hash of an empty array (so that everything can proceed as before)
  - 2 same as before

And again, the lookup to `AccountFieldTag.CodeHash` and `AccountFieldTag.NonExisting` should be conditional and exclusionary.

**Comment by eliseygusev** [comment]
Yeah, thank you. Missing the spec and implementation for EXTCODESIZE was what puzzled me a lot, actually. Will glagly pick up the EXTCODECOPY

**Comment by CPerezz** [comment]
I'm not sure if `SELFDESTRUCT` should be here. Considering [https://eips.ethereum.org/EIPS/eip-6046](EIP6046) I think we should consider first the effors it carries associated and then deicide if we spec and implement the opcode.

One thing that may affect a lot is to know if will be included in `Shanghai` or `Cancun` network updates. Here @barryWhiteHat might have some more insight.

**Comment by eliseygusev** [comment]
The latest status on updating the spec is here:
- EXTCODECOPY -- done in #344 
- EXTCODESIZE -- done in #341 
- CALL, CALLCODE, DELEGATECALL, and STATICCALL seems to be fixed in #335, am I right?
- SELFDESTRUCT -- temporarily on hold?
- SLOAD, SSTORE -- picked up by @CPerezz

@ed255 am I missing something? can you please update the starting post if all the above is correct?

**Comment by CPerezz** [comment]
@eliseygusev Thanks a lot! I've updated the issue post!
I think with this we're almost done.

**Comment by barryWhiteHat** [comment]
> One thing that may affect a lot is to know if will be included in Shanghai or Cancun network updates. Here @barryWhiteHat might have some more insight.

I suppose we can lower priority on self destruct for now and hope that it gets included in next hard fork. That would be gr8 as it removes some edge cases. I think we should not bet on it being removed by changing our architecture to assume its not there. For example call needs to take the possibility of self destruct into account to allow for an account to be executed with different code an attacker can use self destruct + create2 to change an accounts code. 

If we get to a point where we are ready to make proofs of validity before hardfork to deactivate self destruct then we can implement it.  

My only concern is on the rollup side is self destruct important to implement ? Maybe someone with knowledge of this can give some input @icemelon

**Comment by CPerezz** [comment]
@ChihChengLiang let's make sure `SELFDESTRUCT` is on hold until we see if will be included in the Cancun hardfork or not. That will let us focus on other stuff that will definitely not vary in the close future.

**Comment by ashWhiteHat** [comment]
Take `CALL`

**Comment by ed255** [comment]
This week @han0110 @CPerezz and me discussed the approach we have to handle non-existing accounts between the evm-state-mpt circuits; based on some concerns raised by Han.  Here are the notes: https://hackmd.io/5FHDL-6RSRCOd5l_GMndZA?both

Han found that using the `NonExisting` tag for account could be problematic because it doesn't behave as a state property that can change.  Since the state circuit sorts the RwTable by tag, all NonExisting entries for an account will be together.  This means that a NonExisting lookup happening after an account is created would be put together with NonExisting lookups happening before the account was created.  And all of them would succeed.

In more detail:
Imagine the following trace:
- EXTCODEHASH(A) -> 0 // Account doesn't exist
- CREATE(A) // Create account A
- EXTCODEHASH(A) -> 0 // Invalid result for this step because account A now exists, but the constraints will pass...

List of RwOps chronologically:
- 1, Account, NonExisting, A
- 2, Account, CodeHash, A, 0 -> H
- 3, Account, NonExisting, A

List of RwOps sorted:
- 1, Account, NonExisting, A
- 3, Account, NonExisting, A
- 2, Account, CodeHash, A, 0 -> H

List of MPT lookups from state circuit:
- from [1,3]: NonExistAccountMod, A
- from [2]   : CodeHashMod, A, 0 -> H

---

The solution is to track a state for account existence; and all opcodes that can deal with non-existing accounts must check this state before proceeding with the existence account field lookups.  After some discussion we found that we don't need to introduce a new FieldTag for this, and we can reuse CodeHash == 0 to signal account non-existence (and CodeHash != 0 for account existence).  This is because an existing account will never have CodeHash = 0 (this is guaranteed by the CodeHash writes that the EVM circuit can emit).

So in summary, for account we will treat a CodeHash read with value 0 as the account non-existence proof; and the state circuit will handle this with the `NonExistingAccountProof` tag for the MPT table lookup.  This is easily achieved by changing the mpt lookup in the state circuit for account like this:
```python
if committed_value == 0 and value == 0 and key == CodeHash:
    mpt_lookup(NonExistingAccountProof, key)
else:
    mpt_lookup({NonceMod,BalanceMod,CodeHashMod}, key, committed_value, value)
``` 

For the Storage side, the solution is a bit easier and transparent from the EVM circuit side (and it was already implemented in the spec).  The mpt lookup in the state circuit for storage looks like this:
```python
if committed_value == 0 and value == 0:
    mpt_lookup(NonExistingStorageProof, key)
else:
    mpt_lookup(StorageMod, key, committed_value, value)
```
This allows the EVM circuit to perform SLOAD with 0 and SSTORE 0->0, and the state circuit will translate them to non-existence proofs from the MPT circuit.

# Changes

This is the list of changes that need to be done to fulfill this issue

## Storage
- State circuit specs: no change (NonExistingStorageProof case already done)
- Circuit: apply the spec (NonExistingStorageProof case)
- SLOAD/SSTORE specs + circuit: no change

## Account
- State circuit specs: apply NonExistingAccountProof case (when committed_value == 0 and value == 0 and key == CodeHash)
- Circuits: update from specs
- specs table: remove Account-NonExisting from RwTable
- BALANCE, EXTCODEHASH, EXTCODECOPY, EXTCODESIZE, CALLCODE, DELEGATECALL, STATICCALL
    - Specs: Replace usage of `NonExisting` tag by lookup to `CodeHash` with `IsZero` check.
    - Circuits: Implement the same logic as specs (BALANCE was already upldated with `NonExisting`, needs to be changed)
- CALL
    - Do lookup to `CodeHash` with `IsZero` check.

**Comment by ed255** [comment]
I'm working on updating the specs following https://github.com/privacy-scaling-explorations/zkevm-specs/issues/259#issuecomment-1372429829
