### ISSUE TITLE
`RETURNDATACOPY` spec

### ISSUE THREAD

**Issue by Brechtpd** [privacy-scaling-explorations/zkevm-specs#262]
Will be done by @xiaodino and @smtmfft

**Comment by ashWhiteHat** [comment]
Hi @Brechtpd 
We already have RETURNDATACOPY spec.
https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/opcode/3eRETURNDATACOPY.md

Could you close this issue if this was completed?

**Comment by Brechtpd** [comment]
Ah sorry, forgot to close this issue. Done in https://github.com/privacy-scaling-explorations/zkevm-specs/pull/274.

**Comment by ashWhiteHat** [comment]
Thank you!
