### ISSUE TITLE
State circuit "start" tag constraints fix

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-specs#275]
Currently the constraints for the `Start` tag are:
```python
def check_start(row: Row, row_prev: Row):
    # 1.0. rw_counter is 0
    assert row.rw_counter == 0
```
We defined to have sequential rwc in `Start` to prove a lower bound on padding rows.  And there should be also more constraints verifying that some of the columns are 0, that the root doesn't change, etc.

See https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/7d2c05146baaf8662d607574c44a796127e80c16/zkevm-circuits/src/state_circuit/constraint_builder.rs#L161 for reference (as this is correctly done in the circuit)

Spotted this issue here https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/766#discussion_r972159319

**Comment by aguzmant103** [comment]
Note: created PR and is in review. #339
