### ISSUE TITLE
Precompile: 0x01 ecRecover

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-specs#318]

**Comment by ed255** [comment]
For this precompile we should leverage on the work done in halo2wrong: the ECDSA verification: https://github.com/privacy-scaling-explorations/halo2wrong/blob/63bde545d934e69c806ef9bc8b18f03f6ec0fe8e/ecdsa/src/ecdsa.rs#L91

The linked ECDSA verification circuit only passes the constraints when the verification succeeds.  In `ecRecover` an invalid signature can be used, so the verification circuit will need to be modified to support invalid signatures as well.

**Comment by ChihChengLiang** [comment]
Scroll has some progress on ecRecover 

- https://github.com/scroll-tech/zkevm-circuits/issues/527
- https://github.com/scroll-tech/zkevm-circuits/pull/529

**Comment by KimiWu123** [comment]
Two related PRs
- https://github.com/scroll-tech/zkevm-circuits/pull/529
- https://github.com/scroll-tech/zkevm-circuits/pull/930
