### ISSUE TITLE
Precompile: 0x06 ecAdd

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-specs#323]
Probably some of the wrong curve circuit logic would be useful here. https://github.com/privacy-scaling-explorations/halo2wrong

**Comment by KimiWu123** [comment]
Scroll team' implementation: https://github.com/scroll-tech/zkevm-circuits/pull/598 and a path, https://github.com/scroll-tech/zkevm-circuits/pull/811

**Comment by roynalnaruto** [comment]
@KimiWu123 @ChihChengLiang  to summarise our implementation for `ecAdd`, `ecMul` and `ecPairing`:
- Inputs to the above precompiles are fed as witness to the [`EccCircuit`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/ecc_circuit.rs)
- We then copy those advices to the [`EccTable`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/table.rs#L2334-L2373)
- We validate calls to those precompiles through:
    - EVM Circuit [`CallOp`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/execution/callop.rs#L309)
    - [`PrecompileGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/util/precompile_gadget.rs)
    - And individual verification gadgets, in the above cases:
        - [`EcAddGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_add.rs)
        - [`EcMulGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_mul.rs)
        - [`EcPairingGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_pairing.rs)

**Comment by KimiWu123** [comment]
> @KimiWu123 @ChihChengLiang to summarise our implementation for `ecAdd`, `ecMul` and `ecPairing`:
> 
> * Inputs to the above precompiles are fed as witness to the [`EccCircuit`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/ecc_circuit.rs)
> * We then copy those advices to the [`EccTable`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/table.rs#L2334-L2373)
> * We validate calls to those precompiles through:
>   
>   * EVM Circuit [`CallOp`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/execution/callop.rs#L309)
>   * [`PrecompileGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/util/precompile_gadget.rs)
>   * And individual verification gadgets, in the above cases:
>     
>     * [`EcAddGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_add.rs)
>     * [`EcMulGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_mul.rs)
>     * [`EcPairingGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_pairing.rs)

@roynalnaruto , thanks for your explanation! I was watching your code and wondering what the difference between individual gadget, like `EcAddGadget` and `PrecompileGadget`? Could you give us more insight of your design? Thanks.

**Comment by lispc** [comment]
i think the core idea here is, we add a new ExecStat for precompiles.  So the ExecStat sequence will be [..., callop, ecadd, ${next_exec_stat}, ... ]. 
Precompiles are not embedded inside callop but uses new ExecStats.   So i think "the difference between individual gadget, like EcAddGadget and PrecompileGadget", one is the standalone exec step gadget, the other is the "gadget embedded inside callop gadget to connect with following real precompile gadget"?

**Comment by KimiWu123** [comment]
> i think the core idea here is, we add a new ExecStat for precompiles. So the ExecStat sequence will be [..., callop, ecadd, ${next_exec_stat}, ... ]. Precompiles are not embedded inside callop but uses new ExecStats. So i think "the difference between individual gadget, like EcAddGadget and PrecompileGadget", one is the standalone exec step gadget, the other is the "gadget embedded inside callop gadget to connect with following real precompile gadget"?

Understood, just like create/create2, they have their individual gadget but also has logic embedded in `begin_tx`, right?

**Comment by lispc** [comment]
btw we are upgrading halo2-libs we are using from a very old version to latest version.  it may take 3-4 weeks?   So if it is not urgent, it would be better after the upgrade either we or you port the ecXXX precompiles

**Comment by KimiWu123** [comment]
> btw we are upgrading halo2-libs we are using from a very old version to latest version. it may take 3-4 weeks? So if it is not urgent, it would be better after the upgrade either we or you port the ecXXX precompiles

Thanks for your update, we'll hold until you finish the upgrade.

**Comment by KimiWu123** [comment]
> btw we are upgrading halo2-libs we are using from a very old version to latest version. it may take 3-4 weeks? So if it is not urgent, it would be better after the upgrade either we or you port the ecXXX precompiles

Hi @lispc, wondering what the integration progress is now?
