### ISSUE TITLE
Precompile: 0x08 ecPairing

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-specs#325]
@yi-sun might have related work https://github.com/yi-sun/circom-pairing

**Comment by CPerezz** [comment]
Hey @yi-sun. I'd suggest to first try to spec out the pairing precompile circuit and make a PR with the python spec to https://github.com/privacy-scaling-explorations/zkevm-specs

From there, we can move on and start an impl here! :smile:
