### ISSUE TITLE
Better ergonomics for passing auxiliary witness to EVM Step

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-specs#331]
Currently we're passing auxiliary witness data to EVM execution step gadgets usin a field called `aux_data`:
https://github.com/privacy-scaling-explorations/zkevm-specs/blob/d4e50f011f7a6d6d60c24449df75402490f247f1/src/zkevm_specs/evm/step.py#L45

This doesn't always look very clear in the gadget itself, because the only way to know what `aux_data` is holding is by looking at the test and seeing what is being assigned to it.

Since python is a dynamically typed language, maybe we could find a way to use a dynamic field name that properly describes the `aux_data` meaning.  For example, we could still have `aux_data: Any`, but then do an assignment in the test like this:
```python
AuxData = namedtuple('code_hash')
aux_data = AuxData(code_hash = foo)
```
And then the gadget code would look more readable:
```python
        instruction.constrain_equal(code_hash, instruction.curr.aux_data.code_hash)
```

Another option is to make `aux_data` a dictionary from `string` to `Any`

**Comment by eliseygusev** [comment]
Another option worth considering here is the TypeVar: https://docs.python.org/3/library/typing.html#typing.TypeVar 
For instance, one can make BaseClass (pydantic) for any AuxData (and this type would be passed to TypeVar check), with different kinds of aux data deriving from the base class. TypeVar allows expecting the exact type passed to the function and is not as ambiguous as "Any"
for instance the line:
```python
instruction.constrain_equal(code_hash, instruction.curr.aux_data)
```
could look like
```python
aux_code_hash: CodeHash = instruction.curr.aux_data
instruction.constrain_equal(code_hash, aux_code_hash)
```

**Comment by CPerezz** [comment]
That's a nice idea @eliseygusev !!!

I was considering an enum-based solution which depending on the opcode(enum case) it carries some data structure or another one. And that can be type-checked correctly.
There are not a lot of cases for what aux-data refers. So this makes it also easier. 

But if you want to pick this and impl the `TypeVar` solution, please feel free to!!

**Comment by CPerezz** [comment]
Do you want to work on this @eliseygusev ??

**Comment by CPerezz** [comment]
> @CPerezz Sorry, missed your message. Sure! I could try to find a solution that works the most conveniently and implement it. Will give an update on that issue, will look into it most likely next week though if that's OK.

Sure!!! No rush! I just asked as otherwise I'll take it!

**Comment by eliseygusev** [comment]
I feel like this issue is not needed now since #259 got closed in favour of the solution using code_hash instead of aux data, is it?

**Comment by CPerezz** [comment]
I agree @eliseygusev ! 
If @ed255 agrees, I think we can close this!

**Comment by ed255** [comment]
I aree as well!
