### ISSUE TITLE
Add mulmod check

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-specs#34]
### Problem

Spec out modular multiplication mulmod(a, b, n) on EVM words a, b, and n

Might depends on #32 

### Solution

See https://hackmd.io/@arielg/B13JoihA8

**Comment by kilic** [comment]
@ChihChengLiang In non native arithmetic side we're closely following the approach from AZTEC team. However our side is actually not very generic and we can easily check some boundaries in construction. For now I'm not sure if it can be simply generalized for very generic mulmod opcode

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-specs/pull/204
