### ISSUE TITLE
missing ErrGasUintOverflow error state

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-specs#347]
need to add it into https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/execution_state.py#L81

**Comment by han0110** [comment]
Since u64 overflow implies out of gas, and all `ErrGasUintOverflow` happens due to memory expansion too much, so I think perhaps we could handle it within out of gas gadgets. How does that sound?

**Comment by DreamWuGit** [comment]
make some sense, but for typical OOG case,  it is not always gas uint overflow. like remaining gas left is 2 gas, but requires 3 for this step, it is typical OOG , but nothing with `ErrGasUintOverflow`,  I concern theres is some gap between these two errors.

**Comment by han0110** [comment]
> make some sense, but for typical OOG case, it is not always gas uint overflow. like remaining gas left is 2 gas, but requires 3 for this step, it is typical OOG , but nothing with ErrGasUintOverflow, I concern theres is some gap between these two errors.

Yes it makes sense, so I guess we need to have some logics in out of gas gadgets like:

```python3
assert (
    not gas_cost_is_in_u64 or
    gas_left < gas_cost
)
```

To make sure both cases are handled properly

**Comment by ashWhiteHat** [comment]
Hi @DreamWuGit 
Are you working on this?
If not, I would fix this.

**Comment by DreamWuGit** [comment]
@ashWhiteHat  I am not doing this now, you can pick it up !

**Comment by ashWhiteHat** [comment]
@DreamWuGit 
Thank you 😀
I pick this up!
