### ISSUE TITLE
Implement `ErrorInvalidOpcode` state

### ISSUE THREAD

**Issue by silathdiir** [privacy-scaling-explorations/zkevm-specs#350]
Suppose to add [ErrorInvalidOpcode](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/execution_state.py#L82) state implementation to [evm/execution](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/execution/__init__.py#L106) as:

1.  Do fixed lookup for invalid opcode.
2. Verify current call is failed.
3. Go to EndTx only when `is_root`.
4. Do step state transition.

**Comment by CPerezz** [comment]
@silathdiir please edit the issue description :smile:

**Comment by silathdiir** [comment]
> @silathdiir please edit the issue description 😄

Sorry. Just updated to a simple description supposed to add.
