### ISSUE TITLE
Design proposal for HI/LO instead of using RLC

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-specs#363]
- [x] (pending) Links with all the content related with this effort
- [x] Come up with a couple of different approaches proposals
- [x] Discuss the theoretical performance (i.e. how many columns, rows and gate degrees we´ll need to add)
- [x] Personally pick one and justify the decision
- [x] Share it on Discord and ask for feedback

Then
- Write specs on circuit on chosen decision

Notes
- Take into consideration all of the places where this is going to take effects
- i.e. regular circuits vs circuits that has constraint builder

After Then consider:
- Come with performance estimations and constraints cost
- And/or a fork/branch implemented with this approach to estimate

**Comment by ed255** [comment]
Here's a document with a proposal on how to refactor word_rlc to word_hi/lo https://hackmd.io/rF-ysYcKRzGO2jFrYeXDnA?both#Proposal-and-changes
The document link points to the proposal itself, and before it there are different analysis of:
- Review of the previous work done by @icemelon (basically my proposal follows the same approach)
- Different approaches and possibilities
- Number of extra columns/rows needed
  - I don't think there will be an increase in constraint degree
  
I would be grateful if someone can review the comment, specially making sure I didn't forget any possible approach!

**Comment by CPerezz** [comment]
Once I close my latest WIP PR, I'll definitely take a look!
Probably input from @han0110 @ChihChengLiang and others is welcome too!

**Comment by aguzmant103** [comment]
Note: encouraging everyone on the team to read this, comment, ask questions if there are doubts, etc :) any feedback welcomed

**Comment by ChihChengLiang** [comment]
I'll be reviewing this next week.

**Comment by ChihChengLiang** [comment]
@ed255 @CPerezz I added a comment on the security concern part. I think if we change the way we lookup the table we can avoid the security concern. 

In the proposal we lookup for hash `A||B` by constraining `[part=lo, CodeHash=A, Tag=Byte, index=0]` and `[part=hi, CodeHash=B, Tag=Byte, index=0]`. This creates the opportunity for the attacker to grind 128-bit collisions of `A||X` and `Y||B` and locate them in two remote rows.

I propose we lookup `A||B` by constraining `[part=lo, CodeHash=A, CodeHash.next=B, Tag=Byte, index=0]` it would solve the problem.

**Comment by ed255** [comment]
Thanks @CPerezz and @ChihChengLiang for all the feedback and discussions! I've extended the analysis to take into account the possibility that CC mentions to perform lookups with rotations to read 2 rows at a time (to resolve the security issue).  Finally we have concluded that we still want to start with just doubling word columns for all tables.

You can read https://hackmd.io/rF-ysYcKRzGO2jFrYeXDnA?both for the full analysis and for options that are discarded for the short term.  The final proposal is as follows:

# Duplicated table columns:

- TxTable -> {Value}
- RwTable -> {StorageKey, Value, ValuePrev}
- Bytecode -> {CodeHash}
- Block -> {Value}
- MPT -> {Key, ValuePrev, Value, RootPrev}
- Keccak -> {Ouput}
- CopyTable -> {Id}

# Lookups changes

- TxTable
    - old: `[$txId, GasPrice, $index, $valueRlc]`
    - new: `[$txId, $tag, $index, $valueLo, $valueHi]`
- Block
    - old: `[$tag, $index, $valueRlc]`
    - new: `[$tag, $index, $valueLo, $valueHi]`
- Keccak
    - old: `[true, $inputRlc, $inputLen, $outputRlc]`
    - old: `[true, $inputRlc, $inputLen, $outputLo, $outputHi]`
- RwTable:
    - old: `[$rwc, $isWrite, $tag, $id, $address, $fieldTag, $storageKeyRlc, $valueRlc, $valuePrevRlc]`
    - new: `[$rwc, $isWrite, $tag, $id, $address, $fieldTag, $storageKeyLo, $storageKeyHi, $valueLo, $valueHi, $valuePrevLo, $valuePrevHi]`
- Bytecode:
    - old: `[$codeHashRlc, $tag, $index, $isCode, $value]`
    - new: `[$codeHashLo, $codeHashHi, $tag, $index, $isCode, $value]`
- CopyTable:
    - old: `[$isFirst, $srcId, $srcTag, $dstId, $dstTag, $srcAddr, $srcAddrEnd, $length, $RlcAcc, $rwc, $rwcInc]`
    - new: same
- MPT:
    - old: `[$addr, $proofType, $keyRlc, $valuePrevRlc, $valueRlc, $RootPrevRlc, $RootRlc]`
    - new: `[$addr, $proofType, $keyLo, $keyHi, $valuePrevLo, $valuePrevHi, $valueLo, $valueHi, $RootPrevLo, $RootPrevHi, $RootHi, $RootLo]`

## EVM Circuit

- ExecStates BYTE
    - Instead of `cb.stack_push(selected_byte)`, do `cb.stack_push(selected_byte, 0)`
- ExecStates COMPARATOR, SIGNED_COMPARATOR
    - Instead of `cb.stack_push(result.expr())` do `cb.stack_push(result.expr(), 0)`
- ExecStates JUMPI, ISZERO
    - Replace `IsZero(word_rlc)` by `IsZero(word_lo) AND IsZero(word_hi)`
- Whenever a word_rlc is decoded
    - Replace `word_rlc = RLC(word_u8, r)` by `word_lo = LINEAR(word_u8[0:16], 2^8)` and `word_hi = LINEAR(word_u8[16:32], 2^8)`
- Replace all gadgets that take `word_rlc` by `word_hi,word_lo`, and follow the decoding as the previous point

## StateCircuit

- StorageKey to limbs
    - Replace `storage_key_rlc = RLC(storage_key_u8, r)` by `storage_key_lo = LINEAR(storage_key_u8[0:16], 2^8)` and `storage_key_hi = LINEAR(storage_key_u8[16:32], 2^8)`
        - Consider using u16 as an optimization to reduce rows

## ExpCircuit

nothing

## CopyCircuit

nothing

## TxCircuit

- Lookup to keccak table: replace `pub_key_hash: RLC` by `pub_key_hash: hi, lo` (and encoding)

## KeccakCircuit

no keccak in specs

## BytecodeCircuit

- Replace `hash` by `hash: hi,lo`

## MPTCircuit

skip for now (circuit not yet merged)

## PiCircuit

Now the BlockTable and TxTable have double column for `Value`.  This affects the `raw_public_inputs` column, as it should grow to contain the contents of these extra columns.

Alternatively we may integrate the PiCircuit from scroll which takes a keccak of the Public Inputs and the transactions are passed also hashed from the RLP encoding.

**Comment by icemelon** [comment]
I made some comments on the hackmd. but the overall design looks great to me.

**Comment by ed255** [comment]
We have now a specific proposal, the next task is to update the specs following the proposal
