### ISSUE TITLE
Specify CREATE & CREATE2

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-specs#371]
Specify CREATE & CREATE2 execution states in the EVM circuit.
Sync with @z2trillion about https://github.com/privacy-scaling-explorations/zkevm-specs/pull/355

**Comment by ashWhiteHat** [comment]
This seems duplicate of https://github.com/privacy-scaling-explorations/zkevm-specs/issues/333

**Comment by aguzmant103** [comment]
@adria0
