### ISSUE TITLE
Copy table out of sync from circuits impl

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-specs#377]
`q_last`, `is_code` and `pad` are missing in the circuits impl. 

We should sync the table description with what we currently have implemented in the circuits.

**Comment by CPerezz** [comment]
This is the current definition of the columns used:
```rust
[
                    (is_first, "is_first"),
                    (id, "id"),
                    (addr, "addr"),
                    (
                        Value::known(F::from(copy_event.src_addr_end)),
                        "src_addr_end",
                    ),
                    (Value::known(F::from(bytes_left)), "bytes_left"),
                    (rlc_acc, "rlc_acc"),
                    (
                        Value::known(F::from(copy_event.rw_counter(step_idx))),
                        "rw_counter",
                    ),
                    (
                        Value::known(F::from(copy_event.rw_counter_increase_left(step_idx))),
                        "rwc_inc_left",
                    ),
                ],
```

**Comment by ed255** [comment]
Ah, let me copy the relevant part that I wrote to the issue regarding the RwTable at https://github.com/privacy-scaling-explorations/zkevm-specs/issues/376#issuecomment-1419391923

> In `copy_table` I think the columns `q_step`, `q_first`, `q_last`, `isCode`, `Pad` are not used in the lookups, so they should be removed from the table definition (and only have them in the CopyCircuit spec md)
