### ISSUE TITLE
Update pi circuit design specs 

### ISSUE THREAD

**Issue by hero78119** [privacy-scaling-explorations/zkevm-specs#409]
Related to https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1344

**Comment by hero78119** [comment]
related to pr https://github.com/privacy-scaling-explorations/zkevm-specs/pull/390

**Comment by ChihChengLiang** [comment]
Pending on the word hi/lo refactor

**Comment by ChihChengLiang** [comment]
Unblocked since #390 is merged.
