### ISSUE TITLE
Rename all instances of RwTableTag by Target

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-specs#422]
`RwTableTag` is replaced by `Target` in the circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1406

We should rename `RwTableTag` to Target for consistency.

 https://github.com/search?q=repo%3Aprivacy-scaling-explorations%2Fzkevm-specs%20RwTableTag&type=code

_Originally posted by @ed255 in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1406#pullrequestreview-1428203917_

**Comment by th3093** [comment]
still open?

**Comment by ChihChengLiang** [comment]
@th3093 The issue is still open. Feel free to take it.

**Comment by th3093** [comment]
Done. Where to PR or commit? Sry, this is my first contribution and I don't want to break shit:D

**Comment by ChihChengLiang** [comment]
Hi @th3093,
Please send a pull request to this repo, i.e. https://github.com/privacy-scaling-explorations/zkevm-specs.

**Comment by th3093** [comment]
Ok did it. Thanks:)

**Comment by ChihChengLiang** [comment]
Fixed in #431
