### ISSUE TITLE
Sync BufferReaderGadget with the circuit

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-specs#440]
In https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1485, bound_dist and bound_dist_is_zero are removed. We also use the sum of selectors for constraints.

Update the spec to reflect the new constraints.

**Comment by NOOMA-42** [comment]
May I pick up this issue?

**Comment by KimiWu123** [comment]
Hi @NOOMA-42, yes, feel free to pick up this issue!

**Comment by ed255** [comment]
Closing following https://github.com/privacy-scaling-explorations/zkevm-specs/pull/494#issuecomment-2036661722
