### ISSUE TITLE
Integrate precompiles into callop

### ISSUE THREAD

**Issue by KimiWu123** [privacy-scaling-explorations/zkevm-specs#498]
Currently, our precompile gadgets are all individual verification gadgets, but we need to integrate these precompile gadgets into `callop` (bcs precompiles are part of `callop`). Could refer to Scroll's implementation: https://github.com/scroll-tech/zkevm-circuits/blob/2e06a0f4d089c2c01f2f62f44dc4a2ed354f4d28/zkevm-circuits/src/evm_circuit/execution/callop.rs#L315-L523

**Comment by ChihChengLiang** [comment]
I can confirm the precompile part of the callop gadget is handled in #1628
See https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1628/files#diff-e72a6a818cbda6c14cb551573432e59fe61ce109345dd4c088508a60c27979af

**Comment by KimiWu123** [comment]
Yep, this is about the spec not the circuit. 😄
