### ISSUE TITLE
Refactor: clean up duplicated keccak_table

### ISSUE THREAD

**Issue by KimiWu123** [privacy-scaling-explorations/zkevm-specs#499]
We have duplicated keccak_table in different place. The main goal of this issue is to merge them into one. Here are some previous comments:
https://github.com/privacy-scaling-explorations/zkevm-specs/pull/488#discussion_r1336018171
https://github.com/privacy-scaling-explorations/zkevm-specs/pull/495#discussion_r1372513064

**Comment by mmjahanara** [comment]
Hey @KimiWu123 
If this issue is still open, I'd like to take a stab at it!

**Comment by KimiWu123** [comment]
Hi @mmjahanara,  this issue is still open and feel free to take it!

**Comment by ChihChengLiang** [comment]
Close for we are deprecating Python implementation #518
