### ISSUE TITLE
State and storage trie opening and incrementally update

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-specs#56]
In State circuit we need to verify each used `account` and `storage_slot` have correct previous value: `rlp([nonce, balance, code_hash, storage_trie_hash])` and `value` respectively, with merkle patricia trie proofs, and then update each key incrementally.

The following should be described as part of [`specs/circuits/state.md`](TBD):

- How to incrementally update the trie
- How it uses circuit `mpt` (`merkle_patricia_trie`) by lookup

**Comment by ed255** [comment]
This has already been specified:
https://github.com/privacy-scaling-explorations/zkevm-specs/blob/08c6c30a7b53f83558a7ea7e50dc0e4d74fab0c8/src/zkevm_specs/state.py#L266-L268
https://github.com/privacy-scaling-explorations/zkevm-specs/blob/08c6c30a7b53f83558a7ea7e50dc0e4d74fab0c8/src/zkevm_specs/state.py#L307-L309
