### ISSUE TITLE
Add EQ to LT & GT opcode

### ISSUE THREAD

**Issue by miha-stopar** [privacy-scaling-explorations/zkevm-specs#62]
LT gadget implementation is being modified [here](https://github.com/appliedzkp/zkevm-circuits/pull/120). We need to make the specs to reflect these changes (for example EQ is to be added).

**Comment by ed255** [comment]
Done in https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/opcode/lt_gt.py
