### ISSUE TITLE
handle call related opcodes

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-specs#86]
- [x] `0x33`: `CALLER`: call context lookup, stack push https://github.com/appliedzkp/zkevm-specs/pull/90
- [x] `0x34`: `CALLVALUE`: call context lookup, stack push https://github.com/appliedzkp/zkevm-specs/pull/96
- [x] `0x35`: `CALLDATALOAD`: call context lookup + index, stack push @CPerezz 
- [x] `0x36`: `CALLDATASIZE`: call context lookup, stack push https://github.com/appliedzkp/zkevm-specs/pull/96
- [x] `0x37`: `CALLDATACOPY`: multi step: call context lookup + index, memory write @icemelon https://github.com/appliedzkp/zkevm-specs/pull/111

**Comment by icemelon** [comment]
I'm working on the `CALLDATACOPY` and the circuit part is almost done. Will refactor the previous [spec](https://github.com/appliedzkp/zkevm-specs/pull/63) based on the circuit implementation next week.

**Comment by ed255** [comment]
I'm going to work on `CALLVALUE`, `CALLDATALOAD` and `CALLDATASIZE`.

**Comment by roynalnaruto** [comment]
@ed255 Are you also going to do the circuit for `CALLDATASIZE` in the [Circuits Repo](https://github.com/appliedzkp/zkevm-circuits) ?

I already had a [WIP Draft PR](https://github.com/scroll-tech/zkevm-circuits/pull/80) which I can continue finishing if you haven't started working on it :)

**Comment by ed255** [comment]
> @ed255 Are you also going to do the circuit for `CALLDATASIZE` in the [Circuits Repo](https://github.com/appliedzkp/zkevm-circuits) ?

I was planning to but I haven't started yet :P

> I already had a [WIP Draft PR](https://github.com/scroll-tech/zkevm-circuits/pull/80) which I can continue finishing if you haven't started working on it. I can follow the the specs you've added in your `CALLDATASIZE` specs PR.

Please continue working on it!

I did start working on the `CALLVALUE` circuit implementation, so I'll continue that :)

**Comment by CPerezz** [comment]
`CALLDATALOAD` is still missing. We should wait until we merge specs for it to close this issue no? @ChihChengLiang

**Comment by ChihChengLiang** [comment]
Yeah, sorry github auto merge it. Let's wait for the CALLDATALOAD
